import 'server-only';
import { createHash } from 'node:crypto';
import { PlatformError } from '@/lib/errors';
import {
  MAX_RESULTS_PER_QUERY,
  type ResearchProvider,
  type SearchQuery,
  type SearchResponse,
  type SearchResult,
} from './provider';

/**
 * Deterministic research provider for tests and local development.
 *
 * Everything it returns is derived from a hash of the query, so the same query
 * always produces the same results — which is what makes an end-to-end test of
 * the pipeline meaningful rather than flaky.
 *
 * Two deliberate properties:
 *
 * It never returns a real company's name or a real URL. Every result points at
 * a subdomain of `example.invalid`, a TLD reserved by RFC 2606 precisely so it
 * can never resolve. If this provider ever ran in production, the report would
 * be visibly, unmistakably fake rather than plausibly wrong — and the SSRF
 * guard would refuse to fetch any of it anyway. Plausible fake data is the
 * dangerous kind.
 *
 * It can be told to fail. Every error path in the pipeline — provider outage,
 * rate limit, nothing found — needs a test, and the only way to test them
 * without a real outage is to ask for one.
 */

export type MockFault = 'unavailable' | 'rate-limited' | 'empty' | 'slow' | null;

export class MockResearchProvider implements ResearchProvider {
  readonly name = 'mock';
  readonly isLive = false;

  /**
   * Fault injection, set by tests.
   *
   * Static because the pipeline resolves its own provider and tests do not get
   * to hand one in. Reset it in afterEach.
   */
  static fault: MockFault = null;

  /** Recorded queries, so a test can assert what the pipeline asked for. */
  static queries: SearchQuery[] = [];

  static reset(): void {
    MockResearchProvider.fault = null;
    MockResearchProvider.queries = [];
  }

  async search(query: SearchQuery, signal: AbortSignal): Promise<SearchResponse> {
    MockResearchProvider.queries.push(query);

    if (signal.aborted) {
      throw new PlatformError('JOB_TIMEOUT', 'Cancelled before the search started');
    }

    switch (MockResearchProvider.fault) {
      case 'unavailable':
        throw new PlatformError(
          'RESEARCH_PROVIDER_UNAVAILABLE',
          'Injected provider outage',
        );
      case 'rate-limited':
        throw new PlatformError('RESEARCH_PROVIDER_RATE_LIMITED', 'Injected rate limit');
      case 'empty':
        return {
          query: query.query,
          results: [],
          usage: { credits: 0, latencyMs: 1 },
          provider: this.name,
        };
      case 'slow':
        await new Promise<void>((resolve, reject) => {
          const timer = setTimeout(resolve, 60_000);
          signal.addEventListener(
            'abort',
            () => {
              clearTimeout(timer);
              reject(new PlatformError('JOB_TIMEOUT', 'Cancelled during a slow search'));
            },
            { once: true },
          );
        });
        break;
      default:
        break;
    }

    const count = Math.min(query.maxResults, MAX_RESULTS_PER_QUERY);
    const results: SearchResult[] = [];

    for (let i = 0; i < count; i += 1) {
      const seed = createHash('sha256').update(`${query.query}::${i}`).digest('hex');

      // A stable pseudo-company name, drawn from the hash rather than a list,
      // so results vary with the query but never accidentally name a real firm.
      const slug = `${PREFIXES[byte(seed, 0) % PREFIXES.length]}${
        SUFFIXES[byte(seed, 1) % SUFFIXES.length]
      }`;
      const host = `${slug.toLowerCase()}-${seed.slice(0, 6)}.example.invalid`;

      results.push({
        title: `${slug} — ${TITLES[byte(seed, 2) % TITLES.length]}`,
        url: `https://${host}/${PATHS[byte(seed, 3) % PATHS.length]}`,
        excerpt:
          `${slug} is a fictional organisation generated by the mock research provider for query ` +
          `"${query.query.slice(0, 80)}". No part of this describes a real business.`,
        publishedDate: null,
        // Descending, so ranking logic downstream has something to order by.
        score: Math.max(0.05, 1 - i * 0.05),
      });
    }

    return {
      query: query.query,
      results,
      usage: { credits: 0, latencyMs: 1 },
      provider: this.name,
    };
  }
}

function byte(hex: string, index: number): number {
  return parseInt(hex.slice(index * 2, index * 2 + 2), 16);
}

const PREFIXES = [
  'North',
  'Vale',
  'Ash',
  'Kestrel',
  'Harbour',
  'Lumen',
  'Ridge',
  'Quill',
];
const SUFFIXES = ['works', 'field', 'grove', 'point', 'bridge', 'stone', 'craft', 'line'];
const TITLES = [
  'About us',
  'Pricing',
  'Services',
  'Customer stories',
  'Company profile',
  'Contact',
];
const PATHS = ['about', 'pricing', 'services', 'case-studies', 'contact', ''];
