import { z } from 'zod';
import { siteFactsSchema } from './facts';

/**
 * The audit contract.
 *
 * Two halves, deliberately separated:
 *
 *   facts    — measured by the crawler (see schemas/facts.ts)
 *   analysis — generated by the AI, and *only* interpretation
 *
 * The AI never reports a measurement; it explains one. `evidence` on each issue is
 * how the UI proves that: it renders the real extracted value beside the model's
 * commentary, so a hallucinated finding has nowhere to hide.
 *
 * Bump SCHEMA_VERSION whenever a stored report's shape changes. Old rows keep
 * their original version and stay readable.
 */
export const SCHEMA_VERSION = 1;

/* ────────────────────────────── Enums ────────────────────────────── */

export const severitySchema = z.enum(['critical', 'high', 'medium', 'low']);
export const categorySchema = z.enum([
  'technicalSEO',
  'onPageSEO',
  'content',
  'performance',
  'mobile',
  'userExperience',
]);
export const impactSchema = z.enum(['high', 'medium', 'low']);
export const effortSchema = z.enum(['low', 'medium', 'high']);
export const confidenceSchema = z.enum(['high', 'medium', 'low']);
export const basisSchema = z.enum(['measured', 'heuristic', 'inferred']);
export const ratingSchema = z.enum(['excellent', 'good', 'needsImprovement', 'poor']);
export const ownerSchema = z.enum(['developer', 'marketer', 'owner', 'designer']);
export const opportunityTypeSchema = z.enum([
  'seo',
  'content',
  'conversion',
  'technical',
  'growth',
]);

export type Severity = z.infer<typeof severitySchema>;
export type Category = z.infer<typeof categorySchema>;
export type Impact = z.infer<typeof impactSchema>;
export type Effort = z.infer<typeof effortSchema>;
export type Confidence = z.infer<typeof confidenceSchema>;
export type Basis = z.infer<typeof basisSchema>;
export type Rating = z.infer<typeof ratingSchema>;
export type Owner = z.infer<typeof ownerSchema>;
export type OpportunityType = z.infer<typeof opportunityTypeSchema>;

export const CATEGORY_ORDER: readonly Category[] = [
  'technicalSEO',
  'onPageSEO',
  'content',
  'performance',
  'mobile',
  'userExperience',
] as const;

export const SEVERITY_ORDER: readonly Severity[] = [
  'critical',
  'high',
  'medium',
  'low',
] as const;

export const CATEGORY_LABELS: Record<Category, string> = {
  technicalSEO: 'Technical SEO',
  onPageSEO: 'On-Page SEO',
  content: 'Content',
  performance: 'Performance',
  mobile: 'Mobile',
  userExperience: 'User Experience',
};

export const SEVERITY_LABELS: Record<Severity, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

export const OWNER_LABELS: Record<Owner, string> = {
  developer: 'Developer',
  marketer: 'Marketer',
  owner: 'Business owner',
  designer: 'Designer',
};

export const RATING_LABELS: Record<Rating, string> = {
  excellent: 'Excellent',
  good: 'Good',
  needsImprovement: 'Needs Improvement',
  poor: 'Poor',
};

/* ──────────────────────── Scoring constants ──────────────────────── */

/** Ordered high→low; first band whose `min` is met wins. */
export const RATING_BANDS = [
  { min: 90, rating: 'excellent' },
  { min: 75, rating: 'good' },
  { min: 50, rating: 'needsImprovement' },
  { min: 0, rating: 'poor' },
] as const satisfies readonly { min: number; rating: Rating }[];

/**
 * Category weights for the computed overall score.
 *
 * Performance and Mobile are weighted down in V1 because we infer them from HTML
 * signals rather than measuring them. When PageSpeed data lands, `basis` flips to
 * 'measured' and these weights should be rebalanced upward.
 *
 * Must sum to 1.
 */
export const CATEGORY_WEIGHTS: Record<Category, number> = {
  technicalSEO: 0.2,
  onPageSEO: 0.25,
  content: 0.2,
  performance: 0.1,
  mobile: 0.1,
  userExperience: 0.15,
};

/** Coordinates for the impact/effort quadrant. Real enum data, not invented precision. */
export const IMPACT_EFFORT_COORDS = {
  impact: { low: 1, medium: 2, high: 3 },
  effort: { low: 1, medium: 2, high: 3 },
} as const;

export function ratingForScore(score: number): Rating {
  const clamped = Math.max(0, Math.min(100, score));
  for (const band of RATING_BANDS) {
    if (clamped >= band.min) return band.rating;
  }
  return 'poor';
}

/* ──────────────────────── Analysis (AI-generated) ──────────────────────── */

/** Kebab-case slug used for anchors, filtering and cross-references. */
const slugSchema = z
  .string()
  .min(3)
  .max(50)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'must be lowercase kebab-case');

export const evidenceSchema = z.object({
  /** What the value is, e.g. "Meta description". */
  label: z.string().min(1).max(60),
  /** The real extracted value, or an explicit marker like "(absent)". */
  value: z.string().min(1).max(400),
  /** Dot-path into SiteFacts, e.g. "meta.description". Null when not addressable. */
  factPath: z.string().max(80).nullable(),
});

export const issueSchema = z.object({
  id: slugSchema,
  severity: severitySchema,
  category: categorySchema,
  title: z.string().min(3).max(90),
  finding: z.string().min(10).max(500),
  whyItMatters: z.string().min(10).max(500),
  recommendation: z.string().min(10).max(700),
  expectedImpact: z.string().min(5).max(240),
  impact: impactSchema,
  effort: effortSchema,
  owner: ownerSchema,
  confidence: confidenceSchema,
  /** Required for critical/high severity — enforced in the cross-reference pass. */
  evidence: evidenceSchema.nullable(),
});

export const strengthSchema = z.object({
  id: slugSchema,
  category: categorySchema,
  title: z.string().min(3).max(90),
  detail: z.string().min(10).max(400),
});

export const topPrioritySchema = z.object({
  rank: z.number().int().min(1).max(5),
  /** Must reference an existing issues[].id — enforced in the cross-reference pass. */
  issueId: slugSchema,
  rationale: z.string().min(10).max(300),
});

export const actionItemSchema = z.object({
  id: slugSchema,
  title: z.string().min(3).max(90),
  description: z.string().min(10).max(400),
  /** Each must reference an existing issues[].id. */
  issueIds: z.array(slugSchema).max(5),
  owner: ownerSchema,
  effort: effortSchema,
});

export const opportunitySchema = z.object({
  id: slugSchema,
  type: opportunityTypeSchema,
  title: z.string().min(3).max(90),
  description: z.string().min(10).max(500),
  rationale: z.string().min(10).max(300),
  impact: impactSchema,
  effort: effortSchema,
});

export const limitationSchema = z.object({
  id: slugSchema,
  area: z.string().min(3).max(60),
  detail: z.string().min(10).max(300),
  howToResolve: z.string().max(240).nullable(),
});

export const categoryScoreSchema = z.object({
  score: z.number().int().min(0).max(100),
  confidence: confidenceSchema,
  basis: basisSchema,
  summary: z.string().min(10).max(240),
});

export const auditAnalysisSchema = z.object({
  website: z.object({
    name: z.string().min(1).max(80),
    industry: z.string().min(1).max(60),
    description: z.string().min(10).max(300),
    targetAudience: z.string().max(200).nullable(),
  }),

  executiveSummary: z.object({
    headline: z.string().min(10).max(120),
    summary: z.string().min(50).max(900),
    biggestStrength: z.string().min(10).max(300),
    biggestWeakness: z.string().min(10).max(300),
    firstThingToDo: z.string().min(10).max(300),
  }),

  categoryScores: z.object({
    technicalSEO: categoryScoreSchema,
    onPageSEO: categoryScoreSchema,
    content: categoryScoreSchema,
    performance: categoryScoreSchema,
    mobile: categoryScoreSchema,
    userExperience: categoryScoreSchema,
  }),

  issues: z.array(issueSchema).min(3).max(20),
  strengths: z.array(strengthSchema).min(1).max(6),
  topPriorities: z.array(topPrioritySchema).min(3).max(5),

  actionPlan: z.object({
    immediate: z.array(actionItemSchema).min(1).max(5),
    next30Days: z.array(actionItemSchema).min(1).max(6),
    next90Days: z.array(actionItemSchema).min(1).max(6),
  }),

  opportunities: z.array(opportunitySchema).min(2).max(6),

  /**
   * Never optional and never empty. A product that audits a homepage and cannot
   * measure page speed must say so — this field is the honesty contract.
   */
  limitations: z.array(limitationSchema).min(1).max(8),
});

export type AuditAnalysis = z.infer<typeof auditAnalysisSchema>;
export type Issue = z.infer<typeof issueSchema>;
export type Strength = z.infer<typeof strengthSchema>;
export type TopPriority = z.infer<typeof topPrioritySchema>;
export type ActionItem = z.infer<typeof actionItemSchema>;
export type Opportunity = z.infer<typeof opportunitySchema>;
export type Limitation = z.infer<typeof limitationSchema>;
export type CategoryScore = z.infer<typeof categoryScoreSchema>;
export type Evidence = z.infer<typeof evidenceSchema>;

/* ──────────────────────── Stored envelope ──────────────────────── */

export const auditMetaSchema = z.object({
  model: z.string().max(80),
  promptVersion: z.string().max(40),
  durationMs: z.number().int().min(0),
  repairAttempts: z.number().int().min(0).max(3),
  inputTokens: z.number().int().min(0),
  outputTokens: z.number().int().min(0),
});

export const auditReportSchema = z.object({
  schemaVersion: z.number().int().positive(),
  publicId: z.string().min(6).max(32),
  url: z.string().max(500),
  domain: z.string().max(255),
  createdAt: z.iso.datetime(),
  /** Computed server-side from categoryScores — never taken from the model. */
  overallScore: z.number().int().min(0).max(100),
  overallRating: ratingSchema,
  facts: siteFactsSchema,
  analysis: auditAnalysisSchema,
  meta: auditMetaSchema,
});

export type AuditReport = z.infer<typeof auditReportSchema>;
export type AuditMeta = z.infer<typeof auditMetaSchema>;

/* ──────────────────────── Audit lifecycle ──────────────────────── */

export const auditStatusSchema = z.enum(['queued', 'running', 'complete', 'failed']);
export type AuditStatus = z.infer<typeof auditStatusSchema>;
